version: "3"
services:
  web:
    build:
      context: ./client
      args:
        - REACT_APP_API_SERVER_URL=http://localhost:8080/api
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
  backend:
    build: ./server
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/rich-neighborhoods
      SPRING_DATASOURCE_USERNAME: rich-neighborhoods
      SPRING_DATASOURCE_PASSWORD: weroinvoiwenr
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQLDialect
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: mysql
    environment:
      MYSQL_USER: rich-neighborhoods
      MYSQL_PASSWORD: weroinvoiwenr
      MYSQL_DATABASE: rich-neighborhoods
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql:ro
volumes:
  dbdata:

